services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - "8000:4000"
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:8.2.3-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - laravel
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  redis_data:
  postgres_data:
